name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential
    - name: Build and test
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTS=ON
        make
        ctest --output-on-failure
